imports:
    - { resource: config.yml }

pimcore:
    cache:
        enabled:              true
        pools:
            redis:
                enabled:              true

                # Redis connection options. See Pimcore\Cache\Pool\Redis\ConnectionFactory
                connection:
                    server:               127.0.0.1
                    port:                 6379
                    database:             0
                    password:             '%redis_prod_password%'
                    persistent:           ''
                    force_standalone:     false
                    connect_retries:      1
                    timeout:              2.5
                    read_timeout:         0
