# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  providers:
    pimcore_user_provider:
      id: app.security.user_provider

  firewalls:
    api:
      anonymous: ~
      provider: pimcore_user_provider
      stateless: true
      guard:
        authenticators:
          - app.security.jwt_authenticator
      json_login:
        check_path: app_auth_login
        failure_handler: app.security.authentication_error_handler
  access_control:
    - { methods: [OPTIONS], roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: /api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: /api/v1/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: /api/v1, roles: ROLE_USER }