services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # tag all serializer services
    _instanceof:
        AppBundle\Serializer\SerializerInterface:
            tags: ['app.api.serializer']

    # auto-register all controllers as services
    AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\EventListener\KernelExceptionListener:
        tags:
            - { name:kernel.event_listener, event: kernel.exception }

    AppBundle\EventListener\KernelResponseListener:
        tags:
            - { name:kernel.event_listener, event: kernel.response }

    AppBundle\Serializer\:
        resource: '../../Serializer'

    # inject all tagged services as parameter into factoy
    AppBundle\Serializer\SerializerFactory:
        arguments: [!tagged 'app.api.serializer' ]

    app.security.user_provider:
        class: Pimcore\Security\User\ObjectUserProvider
        arguments: ['AppBundle\Model\DataObject\User', 'email']

    app.security.jwt_authenticator:
        class: AppBundle\Security\JwtAuthenticator
        arguments:
            - %secret%

    AppBundle\Service\JwtTokenGenerator:
        arguments:
            - %secret%

    app.security.authentication_error_handler:
        class: AppBundle\EventListener\AuthenticationFailureHandler